export { apiRequest, apiRequestStream, type ApiRequestOptions } from './client';
export { apiUrl, ApiConfigError, getApiBaseUrl } from './config';
export {
  ApiError,
  ApiTransportError,
  API_ERROR_CODES,
  classifyApiError,
  isApiError,
  isDeferredErrorCode,
  isKnownApiErrorCode,
  isUnauthorizedError,
  parseApiErrorCode,
  type ApiErrorCode,
  type ClassifiedApiError,
  type DeferredApiErrorCode,
  type KnownApiErrorCode,
  type RateLimitInfo,
} from './errors';
export { buildApiHeaders, createIdempotencyKey, SSE_ACCEPT, type ApiHeaderOptions } from './headers';
export {
  CONSENT_DOCUMENT_CODES,
  CONVERSATION_STATES,
  EVENT_PROP_KEYS,
  NEED_CODES,
  REQUIRED_CONSENT_CODES,
  RESPONSE_ACTS,
  hasServerVisitor,
  isConsentDocumentCode,
  isConversationState,
  isJudgeNotPassed,
  isJudgePassed,
  isNeedCode,
  isResponseAct,
  isServerMode,
  readRequiredDocuments,
  VISIT_CHANNEL_KEYS,
  VISIT_CHANNEL_VALUE_MAX_LENGTH,
  type ApiErrorEnvelope,
  type ApiSuccess,
  type ApiSuccessMeta,
  type ConsentDocumentCode,
  type ConversationState,
  type EventPropKey,
  type JudgeNotPassed,
  type JudgePassed,
  type JudgeResult,
  type NeedCode,
  type RequiredConsentCode,
  type RequiredDocumentsDetails,
  type ResponseAct,
  type ServerAssignedFlags,
  type ServerMode,
  type StartVisitData,
  type StartVisitRequest,
  type VisitChannel,
  type VisitChannelKey,
  type VisitStatusData,
  type VisitorId,
} from './types';
export { getVisit, startVisit } from './visit';
export {
  consumeConversationStream,
  controlConversation,
  conversationErrorMessage,
  createConversation,
  deleteConversation,
  endConversation,
  isLiveFallbackError,
  listAllConversationMessages,
  listConversationMessages,
  sendConversationMessage,
  type CreateConversationData,
  type CrisisEvent,
  type DoneEvent,
} from './conversations';
export { parseSseBlock, readSseStream } from './sse';
export {
  EVENTS_BATCH_MAX,
  EVENTS_BODY_MAX_BYTES,
  LIVE_EVENT_VERSION,
  POSTABLE_EVENT_NAMES,
  SCRIPTED_EVENT_VERSION,
  isMockEventName,
  isPermanentEventError,
  isPostableEventName,
  postEvents,
  sanitizeEventProps,
  splitEventBatches,
  type FunnelEvent,
  type LiveObservationName,
  type PostEventsData,
} from './events';
export {
  buildConsentGrants,
  CONSENT_STATUS_POLL_FALLBACK_MS,
  CONVERSATION_CONTENT_UNTIL_DELETION_OR_WITHDRAWAL,
  consentRecordErrorMessage,
  consentStatusPollDelayMs,
  consentWithdrawErrorMessage,
  DELETION_SCOPES,
  DELETION_STATUSES,
  endsConversationOnWithdraw,
  getConsentStatus,
  recordConsent,
  withdrawConsent,
  type ConsentGrant,
  type ConsentRecord,
  type ConsentRetention,
  type ConsentStatusData,
  type DeletionErrorBody,
  type DeletionRecord,
  type DeletionScope,
  type DeletionStatus,
  type RecordConsentData,
  type WithdrawConsentData,
} from './consent';
